"""add count column to order product association table

Revision ID: d36dc94da650
Revises: b02de45e4c3f
Create Date: 2023-11-28 15:34:23.148547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36dc94da650'
down_revision: Union[str, None] = 'b02de45e4c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_product_association',
        sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_association', 'count')
    # ### end Alembic commands ###
